notifications:
  email: false

dist: bionic

language: c
compiler: gcc
cache: ccache

addons:
  apt:
    packages:
      - autopoint
      - docbook-simple
      - docbook-xsl
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls28-dev
      - libgpgme11-dev
      - libgss-dev
      - libidn2-0-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - libnotmuch-dev
      - libqdbm-dev
      - libsasl2-dev
      - libslang2-dev
      - libssl-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - lua5.2
      - lynx
      - xsltproc

git:
  depth: 3

install:
  - git clone --depth 1 https://github.com/neomutt/travis-build.git ~/config
  - git clone --depth 1 https://github.com/neomutt/neomutt-test-files.git ~/test-files

before_script:
  - ccache --zero-stats
  - export ANSI_CLEAR
  - export -f travis_fold
  - export -f travis_nanoseconds
  - export -f travis_time_finish
  - export -f travis_time_start
  - export NEOMUTT_TEST_DIR="$HOME/test-files"
  - (cd ~/test-files && ./setup.sh)

script:
  - ~/config/build

after_script:
  - ccache --show-stats

